### ISSUE TITLE
Makefile highlighting issue/improvement list

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#3051]
This issue is for tracking notable highlighting issues for Makefile filetype. I've provided screenshot for two more editors to compare.

- [x] - Targets with curly braces are not highlighted: [Kakoune](https://user-images.githubusercontent.com/19470159/62757073-ac418280-ba82-11e9-8602-9192d31b716b.png), [Emacs](https://user-images.githubusercontent.com/19470159/62757082-b82d4480-ba82-11e9-8db2-37ebbb517318.png), [Atom](https://user-images.githubusercontent.com/19470159/62757112-d430e600-ba82-11e9-9cd4-d361e50ecdca.png) (fixed by #3029)
- [x] - Targets with `/` are not highlighted: [Kakoune](https://user-images.githubusercontent.com/19470159/62757217-37bb1380-ba83-11e9-82d0-857bcbf9673c.png), [Emacs](https://user-images.githubusercontent.com/19470159/62757187-1b1edb80-ba83-11e9-9dc8-704ac29fb2d4.png), [Atom](https://user-images.githubusercontent.com/19470159/62757162-080c0b80-ba83-11e9-8781-c6f0064cb697.png) (fixed by #3029)
- [x] - Multiple targets separated with spaces are not highlighted: [Kakoune](https://user-images.githubusercontent.com/19470159/62852752-0e082380-bcf3-11e9-8cb2-ce295834846d.png), [Emacs](https://user-images.githubusercontent.com/19470159/62852740-021c6180-bcf3-11e9-8047-4d09770ec058.png), [Atom](https://user-images.githubusercontent.com/19470159/62852809-2ed07900-bcf3-11e9-8aa2-3a54a4d3b596.png) (fixed by #3029)
- [ ] - Strings are not highlighted: [Kakoune](https://user-images.githubusercontent.com/19470159/62757272-7224b080-ba83-11e9-8efc-deb0cef2d971.png), [Emacs](https://user-images.githubusercontent.com/19470159/62757282-7fda3600-ba83-11e9-9570-eaa314c6576f.png), [Atom](https://user-images.githubusercontent.com/19470159/62757296-908aac00-ba83-11e9-97cb-24889b3b8fe8.png) (tracked by #3052)
- [ ] - Special variables are not highlighted: [Kakoune](https://user-images.githubusercontent.com/19470159/62757327-a7c99980-ba83-11e9-9e0b-546f5076bda1.png), [Emacs](https://user-images.githubusercontent.com/19470159/62757336-ae581100-ba83-11e9-8e14-e27eec1bee57.png), [Atom](https://user-images.githubusercontent.com/19470159/62757349-b617b580-ba83-11e9-9756-7e56592c642c.png) (tracked by #3052)
- [ ] - Special commands are not highlighted: [Kakoune](https://user-images.githubusercontent.com/19470159/62757428-f7a86080-ba83-11e9-8f8a-7aa100040c3e.png), [Emacs](https://user-images.githubusercontent.com/19470159/62757436-00009b80-ba84-11e9-8c38-4dce447c1c0e.png), [Atom](https://user-images.githubusercontent.com/19470159/62757449-0abb3080-ba84-11e9-83c9-2194da454422.png) (tracked by #3052)
- [ ] - include directive isn't highlighted: [Kakoune](https://user-images.githubusercontent.com/19470159/62757500-2e7e7680-ba84-11e9-86d2-073cc8f9b056.png), [Emacs](https://user-images.githubusercontent.com/19470159/62757510-350cee00-ba84-11e9-8e35-2273fd5f742d.png), [Atom](https://user-images.githubusercontent.com/19470159/62757529-3b9b6580-ba84-11e9-9578-953e0285d920.png) (tracked by #3052)

**Comment by lenormf** [comment]
I think item №1 is handled by #3029 as well (the regex uses `\S`).

**Comment by andreyorst** [comment]
Did not read in depth the discussion in #3029, but you're right.

**Comment by lenormf** [comment]
I have a PoC branch I've been working on, needs a bit of cleanup before I can make a PR.

The way strings highlighting would be implemented is to declare shell regions in the recipes and `$(shell …)` scopes, so it would go slightly farther than the requirement, but also potentially not be very robust (many ways to implement a recipe in GNU's book).

**Comment by lenormf** [comment]
I think PR #3052 address all these issues.

**Comment by andreyorst** [comment]
Looks like it. I'm going to test your branch with various makefiles from our project. I'll report in #3052 if I find something weird

**Comment by codesoap** [comment]
№3 is also fixed with #3029.
